<?xml version="1.0"?>
<TeamMentor_Article Metadata_Hash="672462200" Content_Hash="-1498313326">
  <Metadata>
    <Id>fceefe0c-900a-4c29-9c2e-ee662aa9e1f1</Id>
    <Id_History>fceefe0c-900a-4c29-9c2e-ee662aa9e1f1,a1ffa183-ce84-403a-a253-4ad2231ba8db,</Id_History>
    <Library_Id>be5273b1-d682-4361-99d9-6234f2d47eb7</Library_Id>
    <Title>Use Structured Exception Handling</Title>
    <Category>Error and Exception Management</Category>
    <Phase>Implementation</Phase>
    <Technology>Java</Technology>
    <Type>Guideline</Type>
    <DirectLink>Use Structured Exception Handling</DirectLink>
    <Tag />
    <Security_Demand />
    <Author />
    <Priority>2</Priority>
    <Status />
    <Source>SI</Source>
  </Metadata>
  <Content Sanitized="true" DataType="html">
    <Data><![CDATA[<h1>Applies to</h1>
  <ul>
    <li>Applications written using Servlets or JSP.</li>
  </ul>
  <h1>What to Do</h1>
  <p>Use structured exception handling.</p>
  <h1>Why</h1>
  <p>Structured exception handling improves robustness and avoids leaving the application in an inconsistent state. It provides the application more information regarding the encountered error and minimizes the risk of information disclosure.</p>
  <h1>When</h1>
  <p>Structured exception handling should be used any time multiple types of exceptions can be thrown.</p>
  <h1>How</h1>
  <p>Exception handlers should be as specific and relevant as possible. When multiple exceptions are anticipated, the <em>try/catch</em> block should have multiple catch clauses to satisfy each type of exception. For example, if a <em>FileNotFoundException</em> and <em>UnsupportedCallbackException</em> are expected, then there should be an exception handler for each type of exception:</p>
  <pre>try{<br />      ...<br />}<br />catch (FileNotFoundException fnf)<br />{<br />      logger.warning(fnf.toString());<br />}<br />catch (UnsupportedCallbackException uce)<br />{<br />      logger.warning(uce.toString());<br />}<br />finally<br />{<br />      //Execute clean-up routine<br />}</pre>
  <p>
    <strong>Note:</strong> The example above assumes that there is a global exception handling mechanism placed at the root of the code execution.<br /></p>
  <h1>Problem Example</h1>
  <p>The following code shows part of an implementation of a JAAS Login Module. Because the code uses a single exception handler, the application cannot log the exception information appropriately.</p>
  <pre>public boolean login() throws LoginException{<br /><br />      if(callbackHandler == null)<br />      {<br />            throw new LoginException("Authentication failed.");<br />      }<br /><br />      // Prompt strings and echo flag not used in callbacks<br />      Callback[] callbacks = new Callback[2];<br />      callbacks[0] = new NameCallback("User: ");<br />      callbacks[1] = new PasswordCallback("Pass: ", false);<br /><br />      try<br />      {<br />            callbackHandler.handle(callbacks);<br />            NameCallback nameCall = (NameCallback)callbacks[0];<br />            PasswordCallback pwdCall = (PasswordCallback)callbacks[1];<br /><br />            user = nameCall.getName();<br />            char[] tempPass = pwdCall.getPassword();<br />            if(tempPass == null)<br />            {<br />                  pass = null;<br />            }<br />            else<br />            {<br />                  pass = new char[tempPass.length];<br />                  common.copyArray(tempPass, pass);<br />            }<br /><br />            pwdCall.clearPassword();<br /><br />            // Verify credentials<br />            if(validUser())<br />            {<br />                  succeeded = true;<br />                  return true;<br />            }<br />            else<br />            {<br />                  succeeded = false;<br />                  clearCredentials();<br />                  throw new FailedLoginException("Authentication failed.");<br />            }<br />      }<br /><br />      // The application has a single exception handler when<br />      // IOException and UnsupportedCallbackException are expected<br />      catch (Exception e)<br />      {<br />            // Add appropriate logging and exception handling mechanisms.<br /><br />            // Consult the Logging section<br /><br />            throw new LoginException("Authentication failed.");<br />      }<br />}</pre>
  <h1>Solution Example</h1>
  <p>The following code shows part of an implementation of a JAAS Login Module. Because the code uses structured exception handling, the application can log the exception information appropriately.</p>
  <pre>public boolean login() throws LoginException{<br /><br /><br />      if(callbackHandler == null)<br />      {<br />            throw new LoginException("Authentication failed.");<br />      }<br /><br />      // Prompt strings and echo flag not used in callbacks<br />      Callback[] callbacks = new Callback[2];<br />      callbacks[0] = new NameCallback("User: ");<br />      callbacks[1] = new PasswordCallback("Pass: ", false);<br /><br />      try<br />      {<br />            callbackHandler.handle(callbacks);<br />            NameCallback nameCall = (NameCallback)callbacks[0];<br />            PasswordCallback pwdCall = (PasswordCallback)callbacks[1];<br /><br />            user = nameCall.getName();<br />            char[] tempPass = pwdCall.getPassword();<br />            if(tempPass == null)<br />            {<br />                  pass = null;<br />            }<br />            else<br />            {<br />                  pass = new char[tempPass.length];<br />                  common.copyArray(tempPass, pass);<br />            }<br /><br />            pwdCall.clearPassword();<br /><br />            // Verify credentials<br />            if(validUser())<br />            {<br />                  succeeded = true;<br />                  return true;<br />            }<br />            else<br />            {<br />                  succeeded = false;<br />                  clearCredentials();<br />                  throw new FailedLoginException("Authentication failed.");<br />            }<br />      }<br /><br /><br />      // The application uses structured exception handling for<br />      // the expected IOException and UnsupportedCallbackException<br />      catch (IOException ioe)<br />      {<br />            // Add appropriate logging and exception handling mechanisms.<br />            // Consult the Logging section<br /><br />            throw new LoginException("Authentication failed.");<br />      }<br />      catch (UnsupportedCallbackException uce)<br />      {<br />            // Add appropriate logging and exception handling mechanisms.<br /><br />            // Consult the Logging section<br /><br />            throw new LoginException("Authentication failed.");<br />      }<br />      catch (Exception e)<br />      {<br />            // Add appropriate logging and exception handling mechanisms.<br /><br />            // Consult the Logging section<br /><br />            throw new LoginException("Authentication failed.");<br />      }<br />  }</pre>
  <h1>Additional Resources</h1>
  <ul>
    <li>To learn more about Java exceptions, visit: <a href="http://download.oracle.com/javase/tutorial/essential/exceptions/index.htmll">Lesson: Exceptions</a> available from Oracle.</li>
  </ul>]]></Data>
  </Content>
</TeamMentor_Article>